[package]
name = "packsy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.18"
dirs-next = "2.0.0"
